Numerical Python

In [4]:
import numpy as np


In [6]:
np.__version__


'1.21.5'

***All functions in numpy***

In [7]:
# integer array:
a=np.array([1, 4, 2, 5, 3])
a

array([1, 4, 2, 5, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14, 4, 2, 3])


array([3.14, 4.  , 2.  , 3.  ])

In [13]:
x=np.array([1, 2, 3, 4], dtype='float32') #If we want to explicitly set the data type of the resulting array.

In [14]:
print(x)

[1. 2. 3. 4.]


In [15]:
# nested lists multidimensional arrays
np.array([[1,2,3],
[4,5,6],
[7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.array([[10,40,7],[1,2,9]])

array([[10, 40,  7],
       [ 1,  2,  9]])

In [17]:
x=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[10,20,30],
[40,50,60],
[70,80,90]]
])
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [18]:
xy=np.array([[[10,12],[14,18]],[[12,14],[16,18]]])
print(xy)

[[[10 12]
  [14 18]]

 [[12 14]
  [16 18]]]


In [19]:
# Create a length-10 integer array filled with zeros
print(np.zeros(10, dtype=int))
print(np.zeros((2,4), dtype=int))
print(np.zeros((2,4,5), dtype=int))

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]]
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [20]:
# Create a 3x1 floating-point array filled with 1s
a=np.ones(4)
print(a)
a=np.ones(4,dtype=int)
print(a)
a=np.ones((3, 1), dtype=float)
print(a)
a1=np.ones((3,2,4))
print(a1)
b=np.full((3, 2), 99)


[1. 1. 1. 1.]
[1 1 1 1]
[[1.]
 [1.]
 [1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [21]:
print(b)

[[99 99]
 [99 99]
 [99 99]]


In [22]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [23]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 1, stepping by 0.1
# (this is similar to the built-in range() function)
np.arange(0, 1, 0.2) # simillar to seq command in R

array([0. , 0.2, 0.4, 0.6, 0.8])

In [24]:
# Create an array of five values evenly spaced between 0 and 1
print(np.linspace(0, 1, 5))
print(np.linspace(1,100,100))

[0.   0.25 0.5  0.75 1.  ]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


***Simple random data***

In [25]:
# np.random.rand(d0, d1, ..., dn)
np.random.rand(10)

array([0.00968401, 0.53081131, 0.61727536, 0.46116223, 0.91479628,
       0.2365447 , 0.51226272, 0.2990334 , 0.63968543, 0.10288569])

In [26]:
np.random.rand(10,2)


array([[0.23591316, 0.0953    ],
       [0.57216517, 0.61396765],
       [0.64057267, 0.02553178],
       [0.85116115, 0.96271541],
       [0.0782152 , 0.66621567],
       [0.73615038, 0.11506581],
       [0.44278019, 0.92002886],
       [0.91190742, 0.60680613],
       [0.01142561, 0.00469675],
       [0.89046238, 0.70224269]])

In [27]:
# np.random.randn(d0, d1, ..., dn)
np.random.randn(10)

array([-0.43844236, -0.31786708, -0.51192107,  0.41770261,  0.67845281,
        1.56714716,  0.11186518, -0.40780106,  0.10304792, -0.40210365])

In [28]:
np.random.randn(3,4,2)


array([[[-0.02917445,  1.01916461],
        [ 1.58639547, -1.76606305],
        [ 0.07441196, -0.48824039],
        [-1.96351335,  0.73359329]],

       [[-0.86680429, -0.0986438 ],
        [-1.82797555,  1.54160134],
        [ 2.13580748, -0.80133858],
        [-1.39693571,  0.16518394]],

       [[ 0.25378154, -0.96598132],
        [ 0.52338502, -0.3113314 ],
        [ 0.7210964 , -0.45751348],
        [ 1.54331191,  0.67603259]]])

In [30]:
# np.random.randint(low[, high, size, dtype])
# This function of random module is used to generate random integers from inclusive(low) to exclusive(high).
np.random.randint(2)

0

In [31]:
np.random.randint(10,20,size=(3,2))

array([[19, 14],
       [11, 19],
       [15, 11]])

In [32]:
#Create a 10x1 array of uniformly distributed
# random values between 0 and 1
np.random.random((1, 5))

array([[0.7598143 , 0.13352169, 0.32640108, 0.14150331, 0.18534283]])

In [33]:
# choice(a, size=None, replace=True, p=None) # similar to sample command in R
xx=np.array(["PS","NK","VS"])
np.random.choice(xx, (10,3), 1)

array([['NK', 'VS', 'VS'],
       ['PS', 'VS', 'NK'],
       ['NK', 'PS', 'NK'],
       ['PS', 'NK', 'PS'],
       ['VS', 'VS', 'NK'],
       ['NK', 'NK', 'PS'],
       ['VS', 'VS', 'NK'],
       ['VS', 'PS', 'NK'],
       ['NK', 'VS', 'PS'],
       ['NK', 'NK', 'VS']], dtype='<U2')

In [35]:
xx=np.array(["PS","NK","VS"])
np.random.choice(xx, 10, 1, p=(0.9,0.05,0.05))


array(['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS'],
      dtype='<U2')

In [36]:
#help in python
np.random.choice?

**Permutations**

In [37]:
xx=np.array(["PS","NK","VS"])
print(xx)
print(np.random.permutation(xx))
print(xx)

['PS' 'NK' 'VS']
['VS' 'NK' 'PS']
['PS' 'NK' 'VS']


In [38]:
xx=np.array(["PS","VS","NK"])
print(np.random.shuffle(xx))
print(xx)

None
['VS' 'NK' 'PS']


**Random Sample From Various Distributions** 

In [39]:
# binomial(n, p[, size])
n, p = 10, .6
s1= np.random.binomial(n, p, 10)
s1

array([8, 5, 8, 8, 8, 7, 8, 3, 5, 7])

In [40]:
n, p = 10, .6
s1= np.random.binomial(n, p, (10,3))
s1

array([[6, 5, 4],
       [7, 6, 6],
       [5, 8, 7],
       [4, 6, 8],
       [4, 4, 6],
       [8, 6, 7],
       [8, 7, 6],
       [6, 4, 5],
       [5, 5, 5],
       [7, 7, 6]])

In [41]:
#np.random.chisquare(df[, size])
np.random.chisquare(2,10)

array([5.91438367, 6.2422705 , 2.7687907 , 1.91355299, 1.7624309 ,
       1.80043627, 6.687626  , 5.94826999, 0.13749533, 3.29986255])

In [42]:
# np.random.exponential([scale, size])
np.random.exponential(2,5)

array([0.78726762, 2.1343991 , 3.52979622, 0.25799391, 0.09602135])

In [44]:
print(np.random.normal())
print(np.random.normal(0, 1, 10),'\n')

-0.3702686911220611
[ 2.74173224  0.66189037 -0.66832703  0.99101399 -0.77699804  0.13218581
  0.77388156 -0.4663121   0.02106232  0.61852571] 



In [45]:
np.random.normal(10,1,(2,5))

array([[11.2873134 ,  9.85296226, 10.657735  ,  9.65197779, 12.19714512],
       [ 8.45918759,  9.28379557, 11.06756797,  9.6824135 , 10.61024468]])

In [46]:
xx=np.array(["SP","VS","NK"])
xx.dtype

dtype('<U2')

In [47]:
from numpy.random import choice
choice(xx, 10, 1)


array(['VS', 'SP', 'VS', 'VS', 'NK', 'SP', 'NK', 'VS', 'NK', 'NK'],
      dtype='<U2')

In [48]:
#importing in another way
from numpy.random import choice as ch
ch(xx, 10, 1)

array(['VS', 'VS', 'VS', 'SP', 'NK', 'SP', 'NK', 'NK', 'SP', 'SP'],
      dtype='<U2')

In [49]:
a=ch
a(xx, 10, 1)

array(['SP', 'VS', 'SP', 'NK', 'NK', 'SP', 'NK', 'SP', 'NK', 'SP'],
      dtype='<U2')

In [50]:
# Create a 10x1 array of random integers in the interval [0, 100)
print(np.random.randint(0, 100),'\n')
print(np.random.randint(100),'\n')
print(np.random.randint(0, 100, (10, 1)),'\n')
print(np.random.randint(100,size=(10,2)),'\n')


37 

70 

[[13]
 [51]
 [70]
 [ 8]
 [29]
 [84]
 [20]
 [ 8]
 [48]
 [92]] 

[[27 48]
 [24 38]
 [17 24]
 [35 48]
 [71 62]
 [48 30]
 [ 6 25]
 [57 28]
 [ 1 41]
 [67 50]] 



In [51]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

*****Numpy Standard Data Types*****

*Numpy Array Attributes*

In [2]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=10) # One-dimensional array
x2 = np.random.randint(10, size=(3, 8)) # Two-dimensional array
x3 = np.random.randint(10, size=(2, 4, 7)) # Three-dimensional array
print(x1)

[5 0 3 3 7 9 3 5 2 4]


In [3]:
print(x2)
print(x3)

[[7 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3]
 [0 3 5 0 2 3 8 1]]
[[[3 3 3 7 0 1 9]
  [9 0 4 7 3 2 7]
  [2 0 0 4 5 5 6]
  [8 4 1 4 9 8 1]]

 [[1 7 9 9 3 6 7]
  [2 0 3 5 9 4 4]
  [6 4 4 3 4 4 8]
  [4 3 7 5 5 0 1]]]


In [4]:
print("x1 ndim: ", x1.ndim)
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape) #shape of array 3*8
print("x3 size: ", x3.size) #total no. of elements
print("dtype:", x3.dtype) #for data type
print("itemsize:", x1.itemsize, "bytes") #meomery size in byte of each element in array
print("nbytes:", x1.nbytes, "bytes") # total meomery size of array

x1 ndim:  1
x2 ndim:  2
x2 shape: (3, 8)
x3 size:  56
dtype: int32
itemsize: 4 bytes
nbytes: 40 bytes


Array Indexing


In [6]:
print(x1)
print(x1[0])
print("length of x1:",len(x1))
print(x1[9])

[5 0 3 3 7 9 3 5 2 4]
5
length of x1: 10
4


In [7]:
print(x1[9])
x1[-1] #To index from the end of the array, you can use negative indices

4


4

In [8]:
#In a multidimensional array, you access items using a comma-separated tuple of indices:
print(x2)
print(x2[0, 0])
# modification in array
x2[0, 0] = 12
print(x2)


[[7 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3]
 [0 3 5 0 2 3 8 1]]
7
[[12  6  8  8  1  6  7  7]
 [ 8  1  5  9  8  9  4  3]
 [ 0  3  5  0  2  3  8  1]]


In [9]:
x2[0,0] = 3.14159 # this will be truncated!
x2

array([[3, 6, 8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9, 4, 3],
       [0, 3, 5, 0, 2, 3, 8, 1]])

Array Slicing: Accessing Subarrays

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
print(x[:5]) # first five elements
print(x[5:]) # elements after index 5
print(x[4:7]) # middle subarray
print(x[::2]) # every other element
print(x[1::2]) # every other element, starting at index 1
print(x[0::2]) # even numbers

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[0 2 4 6 8]


In [12]:
print(x[::-1]) # all elements, reversed
print(x[5::-2] ) # reversed every other from index 5
print(x[5::2] )


[9 8 7 6 5 4 3 2 1 0]
[5 3 1]
[5 7 9]


**Multidimensional Subarrays**

In [13]:
print(x2)


[[3 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3]
 [0 3 5 0 2 3 8 1]]


In [14]:
print(x2[:2, :3] ,'\n') # two rows, three columns
print(x2[:3, ::2]) # all rows, every other column

[[3 6 8]
 [8 1 5]] 

[[3 8 1 7]
 [8 5 8 4]
 [0 5 2 8]]


In [15]:
x2[::-1, ::-1] #subarray dimensions can even be reversed together

array([[1, 8, 3, 2, 0, 5, 3, 0],
       [3, 4, 9, 8, 9, 5, 1, 8],
       [7, 7, 6, 1, 8, 8, 6, 3]])

In [16]:
print(x2)
print(x2[:, 0]) # first column of x2
print(x2[0, :]) # first row of x2
print(x2[0]) # equivalent to x2[0, :]

[[3 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3]
 [0 3 5 0 2 3 8 1]]
[3 8 0]
[3 6 8 8 1 6 7 7]
[3 6 8 8 1 6 7 7]


In [17]:
x2 = np.random.randint(10, size=(3, 8)) # Two-dimensional array
print(x2)
x2_sub = x2[:2, :2]
print(x2_sub)
x2_sub[0, 0] = 99
print(x2_sub)


[[5 9 3 0 5 0 1 2]
 [4 2 0 3 2 0 7 5]
 [9 0 2 7 2 9 2 3]]
[[5 9]
 [4 2]]
[[99  9]
 [ 4  2]]


In [19]:
print(x2)

[[99  9  3  0  5  0  1  2]
 [ 4  2  0  3  2  0  7  5]
 [ 9  0  2  7  2  9  2  3]]


**Reshaping Arrays**

In [20]:
a=np.arange(1, 10)
print(a)
b=a.reshape((3, 3))
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
x = np.array([1, 2, 3])
# row vector via reshape
print(x.reshape((1, 3)))
print(x)
print(x.shape)

[[1 2 3]]
[1 2 3]
(3,)


In [22]:
# column vector via newaxis
print(x[:, np.newaxis])
x.shape

[[1]
 [2]
 [3]]


(3,)

**Array Concatenation and Splitting**

In [31]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [32]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])
print(grid)
#concatenate along the first axis
np.concatenate([grid, grid])


[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [33]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [34]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [35]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print("upper\n",upper)
print("lower\n",lower)
left, right = np.hsplit(grid, [2])
print("left\n",left)
print("right\n",right)

[1 2 3] [99 99] [3 2 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
upper
 [[0 1 2 3]
 [4 5 6 7]]
lower
 [[ 8  9 10 11]
 [12 13 14 15]]
left
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**Computation on NumPy Arrays**

In [36]:
#The Slowness of Loops
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
print(compute_reciprocals(values))
%timeit compute_reciprocals(values)


[0.16666667 1.         0.25       0.25       0.125     ]
12.8 µs ± 4.94 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
print(1.0 / values)
%timeit (1.0 / values)


[0.16666667 1.         0.25       0.25       0.125     ]
1.46 µs ± 456 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**Exploring NumPy’s UFuncs**

In [38]:
x = np.arange(4)
print(x)
print("x + 5 =", x + 5)
print("x // 2 =", x // 2) # floor division

[0 1 2 3]
x + 5 = [5 6 7 8]
x // 2 = [0 0 1 1]


In [ ]:
x = np.arange(4)
print(x)
print(np.add(x, 2))
x = np.array([-2, -1, 0, 1, 2])
n.absolute

In [40]:
print(Out)

{7: 4, 9: array([[3, 6, 8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9, 4, 3],
       [0, 3, 5, 0, 2, 3, 8, 1]]), 10: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 15: array([[1, 8, 3, 2, 0, 5, 3, 0],
       [3, 4, 9, 8, 9, 5, 1, 8],
       [7, 7, 6, 1, 8, 8, 6, 3]]), 22: (3,), 23: array([1, 2, 3, 3, 2, 1]), 24: array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]]), 25: array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]]), 26: array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]]), 31: array([1, 2, 3, 3, 2, 1]), 32: array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]]), 33: array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]]), 34: array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]]), 39: array([2, 1, 0, 1, 2])}


In [41]:
#Exponents and logarithms
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))
print("3^x =", np.power(x, 3))
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))


x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
3^x = [ 1  8 27]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


**Aggregate functions**

In [42]:
x = np.arange(1, 6)
print(x)
print(np.add.reduce(x))
print(np.sum(x))
print(np.multiply.reduce(x))
print(np.cumsum(x)) # for cumsum
print(np.cumprod(x)) #for cumulative product

[1 2 3 4 5]
15
15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [43]:
#Outer products
x = np.arange(1, 6)
print(x)
print(np.multiply.outer(x, x))
print(np.add.outer(x, x))

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]
